### ISSUE TITLE
Outdated version of six gets installed on system

### ISSUE THREAD

**Issue by tomchop** [google/cloud-forensics-utils#260]
```
======================================================================
ERROR: setUpClass (__main__.EndToEndTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/workspace/libcloudforensics-e2e-gcp/tests/providers/gcp/e2e.py", line 47, in DoTest
    test_func(self, *args, **kwargs)
  File "/tmp/workspace/libcloudforensics-e2e-gcp/tests/providers/gcp/e2e.py", line 97, in setUpClass
    cpu_cores=4)
  File "/tmp/workspace/libcloudforensics-e2e-gcp/libcloudforensics/providers/gcp/forensics.py", line 153, in StartAnalysisVm
    image_project=image_project, image_family=image_family)
  File "/tmp/workspace/libcloudforensics-e2e-gcp/libcloudforensics/providers/gcp/internal/compute.py", line 281, in GetOrCreateAnalysisVm
    instance = self.GetInstance(vm_name)
  File "/tmp/workspace/libcloudforensics-e2e-gcp/libcloudforensics/providers/gcp/internal/compute.py", line 159, in GetInstance
    instances = self.Instances()
  File "/tmp/workspace/libcloudforensics-e2e-gcp/libcloudforensics/providers/gcp/internal/compute.py", line 74, in Instances
    self._instances = self.ListInstances()
  File "/tmp/workspace/libcloudforensics-e2e-gcp/libcloudforensics/providers/gcp/internal/compute.py", line 103, in ListInstances
    gce_instance_client = self.GceApi().instances()
  File "/tmp/workspace/libcloudforensics-e2e-gcp/libcloudforensics/providers/gcp/internal/common.py", line 194, in GceApi
    'compute', self.COMPUTE_ENGINE_API_VERSION)
  File "/tmp/workspace/libcloudforensics-e2e-gcp/libcloudforensics/providers/gcp/internal/common.py", line 143, in CreateService
    cache_discovery=False)
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery.py", line 286, in build
    adc_key_path=adc_key_path,
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/googleapiclient/discovery.py", line 455, in build_from_document
    if isinstance(client_options, six.moves.collections_abc.Mapping):
AttributeError: module 'six.moves' has no attribute 'collections_abc'
```

**Comment by tomchop** [comment]
This was supposed to be fixed in https://github.com/googleapis/google-api-python-client/releases/tag/v1.12.1 (and it was https://github.com/googleapis/google-api-python-client/blob/master/setup.py)
