### ISSUE TITLE
listinstances broken for the Azure provider

### ISSUE THREAD

**Issue by jonathan-greig** [google/cloud-forensics-utils#326]
```
$ cloudforensics az <default_resource_group_name> listinstances
[...]
[2021-07-01 14:42:54,492] [tools.az_cli        ] INFO     Instances found:
Traceback (most recent call last):
  File "/[REDACTED]/.local/share/virtualenvs/cloud-forensics-utils-j02neud9/bin/cloudforensics", line 11, in <module>
    load_entry_point('libcloudforensics==20210531', 'console_scripts', 'cloudforensics')()
  File "[REDACTED]/.local/share/virtualenvs/cloud-forensics-utils-j02neud9/lib/python3.9/site-packages/libcloudforensics-20210531-py3.9.egg/tools/cli.py", line 427, in Main
    parsed_args.func(parsed_args)
  File "/[REDACTED]/.local/share/virtualenvs/cloud-forensics-utils-j02neud9/lib/python3.9/site-packages/libcloudforensics-20210531-py3.9.egg/tools/az_cli.py", line 48, in ListInstances
    logger.info('Name: {0:s}, Boot disk: {1:s}'.format(instance, boot_disk))
TypeError: unsupported format string passed to AZComputeVirtualMachine.__format__
```

Issue is https://github.com/google/cloud-forensics-utils/blob/e010499745273e10bda3f030c734a3469c0a0296/tools/az_cli.py#L46 then https://github.com/google/cloud-forensics-utils/blob/e010499745273e10bda3f030c734a3469c0a0296/tools/az_cli.py#L48 where it trys to format the instance object rather than the instance name (compare to similar in the GCP provider).

**Comment by jonathan-greig** [comment]
Fixed with #327
