### ISSUE TITLE
Google Cloud Functions API name or version (v1) not supported anymore

### ISSUE THREAD

**Issue by hacktobeer** [google/cloud-forensics-utils#421]
https://github.com/google/cloud-forensics-utils/blob/main/libcloudforensics/providers/gcp/internal/function.py#L38

```
Traceback (most recent call last):
  File "/root/turbinia-client/bin/turbiniactl", line 8, in <module>
  File "/root/turbinia-client/lib/python3.6/site-packages/turbinia/turbiniactl.py", line 857, in main
  File "/root/turbinia-client/lib/python3.6/site-packages/turbinia/client.py", line 195, in wait_for_request
  File "/root/turbinia-client/lib/python3.6/site-packages/turbinia/client.py", line 287, in get_task_data
  File "/root/turbinia-client/lib/python3.6/site-packages/libcloudforensics/providers/gcp/internal/function.py", line 81, in ExecuteFunction
  File "/root/turbinia-client/lib/python3.6/site-packages/libcloudforensics/providers/gcp/internal/function.py", line 58, in GcfApi
  File "/root/turbinia-client/lib/python3.6/site-packages/libcloudforensics/providers/gcp/internal/common.py", line 186, in CreateService
  File "/root/turbinia-client/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
  File "/root/turbinia-client/lib/python3.6/site-packages/googleapiclient/discovery.py", line 296, in build
  File "/root/turbinia-client/lib/python3.6/site-packages/googleapiclient/discovery.py", line 404, in _retrieve_discovery_doc
googleapiclient.errors.UnknownApiNameOrVersion: name: cloudfunctions  version: v1
```

**Comment by tomchop** [comment]
Maybe we should also add this to the e2e tests?

**Comment by hacktobeer** [comment]
obsolete
