### ISSUE TITLE
Error when snapshot can't complete correctly

### ISSUE THREAD

**Issue by tomchop** [google/cloud-forensics-utils#98]
```
$ python -m examples.aws_cli copyvolume --volume_id=VOLUMEID --src_account=default --dst_account=blah us-east-2a
Starting volume copy...
 
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/google/home/mbrannock/virtualenv/cloud-forensics-utils/examples/aws_cli.py", line 106, in <module>
    parsed_args.func(parsed_args)
  File "/usr/local/google/home/mbrannock/virtualenv/cloud-forensics-utils/examples/aws_cli.py", line 34, in CreateVolumeCopy
    src_account=args.src_account, dst_account=args.dst_account)
  File "/usr/local/google/home/mbrannock/virtualenv/cloud-forensics-utils/libcloudforensics/aws.py", line 1272, in CreateVolumeCopy
    snapshot, volume_name_prefix='evidence')
  File "/usr/local/google/home/mbrannock/virtualenv/cloud-forensics-utils/libcloudforensics/aws.py", line 427, in CreateVolumeFromSnapshot
    snapshot, volume_name_prefix=volume_name_prefix)
  File "/usr/local/google/home/mbrannock/virtualenv/cloud-forensics-utils/libcloudforensics/aws.py", line 670, in _GenerateVolumeName
    volume_name_prefix, snapshot.name[:truncate_at], volume_id_crc32)
TypeError: 'NoneType' object is not subscriptable
```

**Comment by giovannt0** [comment]
#99
